### ISSUE TITLE
Home page is blank white page reading only "Test".

### ISSUE THREAD

**Issue by tatwell** [chapmanu/signage#145]
Ross reported error around 9am this morning.

**Comment by tatwell** [comment]
Mirabel checked out the server’s yum log and it looks like the Redhat OS ran a monthly automated update around 5am yesterday (Sunday) and somehow knocked the Rails application offline.

**Comment by mirabelrice** [comment]
There are two copies of nginx on the server.

 When the server auto-updated, the wrong version of nginx was started.

**Comment by mirabelrice** [comment]
The issue was the result of the wrong nginx running after a server update.

There are two versions of nginx on the Signage server:

    1. System nginx: /etc/nginx
    2. Signage nginx: /opt/nginx

When the server auto-updated, the system version was started instead of the one signage uses. 

#### To fix:
    
on the production server in  ```/etc/init.d/nginx``` set  ```nginx = /opt/nginx/sbin/nginx```

kill the system nginx master process

set the config file  ```/opt/nginx/sbin/nginx -c /opt/nginx/conf/nginx.conf```

repeat on staging server if needed.

**Comment by tatwell** [comment]
Opened up this ticket to fix init.d script:

- https://github.com/chapmanu/signage/issues/146

**Comment by homeofmatt** [comment]
ADDED NOTE:

If you encounter any errors like this:

`nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)`

This means nginx is *still* running on port 80 (there may have been multiple processes to begin with). You can use `sudo fuser -k 80/tcp` to force kill it.

Then run the above restart command as the root user.
